services:
  api:
    build:
      context: .
      dockerfile: DevsuTestApi/Dockerfile
    ports:
      - "5001:443"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_URLS=http://+:5001
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DevsuAppDb;User=sa;Password=Your_password123;TrustServerCertificate=True;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "11433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
