services:
  api:
    build:
      context: .
      dockerfile: backend/src/Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_URLS=http://+:5002
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Server=sqlserver;Database=DevsuAppDb;User=sa;Password=Your_password123;TrustServerCertificate=True;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "11433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
