services:
  api:
    build:
      context: .
      dockerfile: backend/src/Dockerfile
    container_name: devsu-api
    ports:
      - "5002:5002"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_URLS=http://+:5002
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Server=sqlserver;Database=DevsuAppDb;User=sa;Password=Your_password123;TrustServerCertificate=True;
      - CORS__AllowedOrigins=http://localhost:4200

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "11433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  app:
    build:
      context: ./frontend
    container_name: devsu-app
    ports:
      - "4200:80"
    depends_on:
      - api
    environment:
      - API_URL=http://localhost:5002

volumes:
  sql_data:
